{
 "title": "Cluster performance",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"}) / sum(machine_memory_bytes{kubernetes_io_hostname=~\"kube-worker-.*\"}) * 100",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{kubernetes_io_hostname=~\"kube-worker-.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{kubernetes_io_hostname=~\"kube-worker-.*\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"}[1m])) / sum(machine_cpu_cores{kubernetes_io_hostname=~\"kube-worker-.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"kube-worker.*\"}) / sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"kube-worker.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(machine_memory_bytes{kubernetes_io_hostname=~\"kube-worker-.*\"}) - (count(machine_memory_bytes{kubernetes_io_hostname=~\"kube-worker-auto-scaled.+\"}) OR on() vector(0))",
     "legendFormat": "base"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"kube-worker-.*\"})"
    }
   ]
  }
 ]
}