{
 "title": "Scenario \"overhead\"",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"mirror-layer\",\n    pod=~\"crossplane.*\"\n  }[5m])\n)",
     "legendFormat": "crossplane"
    },
    {
     "expr": "sum by (deployment) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-openstack.*\"\n  }[5m])\n)",
     "legendFormat": "provider-openstack"
    },
    {
     "expr": "sum by (deployment) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-kubernetes.*\"\n  }[5m])\n)\n",
     "legendFormat": "provider-kubernetes"
    },
    {
     "expr": "sum by (deployment) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-dummy-message-service.*\"\n  }[5m])\n)",
     "legendFormat": "provider-message-service"
    }
   ]
  },
  {
   "title": "Transmitted data to external systems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-openstack.*\",\n    interface=\"eth0\"\n  }[5m])\n)",
     "legendFormat": "openstack"
    },
    {
     "expr": "sum by (deployment) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-kubernetes.*\",\n    interface=\"eth0\"\n  }[5m])\n)",
     "legendFormat": "kubernetes"
    },
    {
     "expr": "sum by (deployment) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-dummy-message-service.*\",\n    interface=\"eth0\"\n  }[5m])\n)",
     "legendFormat": "message-service"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (\n  container_memory_usage_bytes{\n    namespace=\"mirror-layer\",\n    pod=~\"crossplane.*\"\n  }\n)\n",
     "legendFormat": "crossplane"
    },
    {
     "expr": "sum by (deployment) (\n  container_memory_usage_bytes{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-openstack.*\"\n  }\n)",
     "legendFormat": "provider-openstack"
    },
    {
     "expr": "sum by (deployment) (\n  container_memory_usage_bytes{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-kubernetes.*\"\n  }\n)",
     "legendFormat": "provider-kubernetes"
    },
    {
     "expr": "sum by (deployment) (\n  container_memory_usage_bytes{\n    namespace=\"mirror-layer\",\n    pod=~\"provider-dummy-message-service.*\"\n  }\n)",
     "legendFormat": "provider-message-service"
    }
   ]
  },
  {
   "title": "Managed entities count over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "state_manager_entity_count", "legendFormat": "managed entities count" }
   ]
  }
 ]
}