{
 "title": "Scenario \"Scale Kubernetes deployments\"",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deploy_name",
    "query": "carts,catalogue,front-end,orders,payment,user,shipping"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "$deploy_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deploy_name" },
  {
   "title": "$deploy_name overutilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "latency [s]" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n  /\n  sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n) > 0.06 or vector(0)",
     "legendFormat": "value"
    },
    {
     "expr": "sum_over_time((\n  (\n    (\n      sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n      /\n      sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n    ) > 0.06\n  ) or vector(0)\n)[30m:])",
     "legendFormat": "duration"
    },
    {
     "expr": "sum_over_time(\n  (\n    (\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      ) - 0.06\n    )\n    * on() (\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      ) > 0.06\n    )\n    or vector(0)\n  )[30m:]\n)",
     "legendFormat": "magnitude"
    },
    {
     "expr": "max_over_time((\n  (\n    (\n      sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n      /\n      sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n    ) > 0.06\n  ) or vector(0)\n)[30m:])\n",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$deploy_name replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"sock-shop\", deployment=\"$deploy_name\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "$deploy_name latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "$deploy_name underutilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "latency [s]" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    (\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      ) < 0.02\n    ) or vector(0)\n  )[30m:]\n)\n",
     "legendFormat": "value"
    },
    {
     "expr": "sum_over_time(\n  (\n    (\n      0.02 -\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      )\n    )\n    * on() (\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      ) < 0.02\n    )\n    or vector(0)\n  )[30m:]\n)\n",
     "legendFormat": "duration"
    },
    {
     "expr": "(\n  (\n    sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n    /\n    sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n  ) < 0.02\n) or vector(0)\n",
     "legendFormat": "magnitude"
    },
    {
     "expr": "max_over_time(\n  (\n    (\n      (\n        sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m]))\n        /\n        sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))\n      ) < 0.02\n    ) or vector(0)\n  )[30m:]\n)\n",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$deploy_name QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"$deploy_name\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "QPS"
    }
   ]
  }
 ]
}