apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 00-sock-shop-ns
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: sock-shop
  providerConfigRef:
    name: provider-config-kubernetes
