apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 00-sock-shop-ns
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: carts
        annotations:
              prometheus.io/scrape: 'true'
        labels:
          name: carts
        namespace: sock-shop
      spec:
        ports:
          # the port that this service should serve on
        - port: 80
          targetPort: 80
        selector:
          name: carts
  providerConfigRef:
    name: provider-config-kubernetes
