apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 03-carts-db-dep
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: carts-db
        labels:
          name: carts-db
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: carts-db
        template:
          metadata:
            labels:
              name: carts-db
          spec:
            containers:
            - name: carts-db
              image: quay.io/ibmmas/mongo:4.4.18
              ports:
              - name: mongo
                containerPort: 27017
              securityContext:
                capabilities:
                  drop:
                  - all
                  add:
                  - CHOWN
                  - SETGID
                  - SETUID
              volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
            volumes:
            - name: tmp-volume
              emptyDir:
                medium: Memory
            nodeSelector:
              beta.kubernetes.io/os: linux
  providerConfigRef:
    name: provider-config-kubernetes
