apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 08-catalogue-db-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: catalogue-db
        labels:
          name: catalogue-db
        namespace: sock-shop
      spec:
        ports:
        - port: 3306
          targetPort: 3306
        selector:
          name: catalogue-db
  providerConfigRef:
    name: provider-config-kubernetes
