apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 10-front-end-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: front-end
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: front-end
        namespace: sock-shop
      spec:
        type: NodePort
        ports:
        - port: 80
          targetPort: 8079
          nodePort: 30001
        selector:
          name: front-end
  providerConfigRef:
    name: provider-config-kubernetes
