apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 12-orders-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: orders
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: orders
        namespace: sock-shop
      spec:
        ports:
        - port: 80
          targetPort: 80
        selector:
          name: orders
  providerConfigRef:
    name: provider-config-kubernetes
