apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 22-session-db-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: session-db
        labels:
          name: session-db
        namespace: sock-shop
      spec:
        ports:
        - port: 6379
          targetPort: 6379
        selector:
          name: session-db
  providerConfigRef:
    name: provider-config-kubernetes
