apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 26-user-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: user
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: user
        namespace: sock-shop
      spec:
        ports:
        - port: 80
          targetPort: 80
        selector:
          name: user
  providerConfigRef:
    name: provider-config-kubernetes
