apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: 28-user-db-svc
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: user-db
        labels:
          name: user-db
        namespace: sock-shop
      spec:
        ports:
        - port: 27017
          targetPort: 27017
        selector:
          name: user-db
  providerConfigRef:
    name: provider-config-kubernetes
