{
 "title": "Sock Shop deployments",
 "time": { "from": "2023-12-10T21:27:52.000Z", "to": "2023-12-10T21:52:36.991Z" },
 "templating": {
  "list": [
   {
    "name": "deploy_name",
    "query": "carts,catalogue,front-end,orders,payment,user,shipping"
   }
  ]
 },
 "panels": [
  { "title": "$deploy_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deploy_name" },
  {
   "title": "$deploy_name replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"sock-shop\", deployment=\"$deploy_name\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "$deploy_name latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "$deploy_name QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"$deploy_name\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "QPS"
    }
   ]
  },
  { "title": "$deploy_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$deploy_name replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"sock-shop\", deployment=\"$deploy_name\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "$deploy_name latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"$deploy_name\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"$deploy_name\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "$deploy_name QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"$deploy_name\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "QPS"
    }
   ]
  }
 ]
}