apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  name: stress-test-h1smedium
spec:
  forProvider:
    name: stress-test-h1smedium
    flavorName: h1.smedium
    imageName: Ubuntu-Server-24.04-20250605
    keyPair: default
    region: RegionOne
    network:
      - name: ii-executor-network
        accessNetwork: true
  providerConfigRef:
    name: provider-config-openstack
